### ISSUE TITLE
Emoji Picker popup shows under other elements on the page

### ISSUE THREAD

**Issue by jimmyjacobson** [wedgies/jquery-emoji-picker#1]
I attached Emoji Picker to the question-area text box.  When I click on the emoji picker button, the actual selector shows up under the next form elements.

![screen shot 2015-03-30 at 4 10 23 pm](https://cloud.githubusercontent.com/assets/451248/6909055/63a6ce72-d6f7-11e4-8657-e870aa14d667.png)

**Comment by makenai** [comment]
I've adjusted the z-index.
