### ISSUE TITLE
Multiple Emoji Pickers on One Page Load 

### ISSUE THREAD

**Issue by jimmyjacobson** [wedgies/jquery-emoji-picker#2]
Multiple Emoji Pickers on one /create page seem to be opening only the dropdown for only the first one initialized.

The selected emojis are going into a separate input field than the one being clicked.

![create_a_wedgie](https://cloud.githubusercontent.com/assets/451248/6909178/5605518e-d6f8-11e4-8634-a2bd9b926077.png)

**Comment by makenai** [comment]
Refactored into a more flexible plugin pattern as detailed at http://www.smashingmagazine.com/2011/10/11/essential-jquery-plugin-patterns/

Primarily - created an object instance for each element, and held on to local DOM references internally instead of referencing them by classnames.
