### ISSUE TITLE
Cant upload it to mysql database..Only ??? will be saved.

### ISSUE THREAD

**Issue by nkmswot** [wedgies/jquery-emoji-picker#55]
Tel me the step by step procedure to save to and display from mysql database. Even I have tried with UTF,  utf8mb4_unicode_ci. But nothing would happen. :-1:

**Comment by makenai** [comment]
It's kind of out of the scope for this project - since it's outputting valid UTF8. You might try changing the collation or look at these articles:

https://dev.mysql.com/doc/refman/5.7/en/charset-applications.html
http://jonisalonen.com/2012/ultimate-guide-to-utf8-and-mysql/
