### ISSUE TITLE
How to save in Mysql table? 

### ISSUE THREAD

**Issue by Rinlama** [wedgies/jquery-emoji-picker#56]
I created a column collation utf8mb4_unicode_ci, but it just save as ?????????

**Comment by makenai** [comment]
Duplicate of #55 - sorry this is out of scope for this project.

**Comment by vishnu1991** [comment]
@Rinlama Just go thru this answer on stackoverflow http://stackoverflow.com/a/39465494 
I have tried this  and its working fine !
