### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Radik24** [wedgies/jquery-emoji-picker#62]
HI, 

can You help me with this?
![image](https://user-images.githubusercontent.com/23722745/28705621-f2298d48-7370-11e7-97f0-2aa83f3da6f0.png)

it shows when I open the page and when I click on emoticon, nothing shows

Thanks

**Comment by hkcoyant** [comment]
Hi! @Radik24 you need initialize the input when the document is ready example whit jquery:

```
$(function(){
                                                $('.messenger-msg-text-input').emojiPicker({
                                                    height: '300px',
                                                    width:  '450px'
                                                });

                                            })
```

**Comment by makenai** [comment]
Correct - this looks like the emoji picker initialization code was execute before it the .messenger-msg-text-input dom element was defined.
